### ISSUE TITLE
GitHub releases

### ISSUE THREAD

**Issue by orhun** [alemidev/scope-tui#3]
I saw that `scope-tui` is already present on crates.io - having releases/tags here on GitHub would be also nice.

It is especially a good thing for distro packagers (e.g. me 😄) that want to make `scope-tui` available for more platforms 🐻

**Comment by alemidev** [comment]
very fair, i retroactively added tags every time i bumped the crate version!

there isn't really a proper changelog from version to version because it wasn't really stable until very recently

i only made one github release, older versions are incomplete or buggy anyway

i hope this helps! let me know if i missed something or could add anything else (:

**Comment by orhun** [comment]
Awesome! Can you also commit `Cargo.lock`? It is needed because this is a binary application and we need to track dependencies.

See #5

**Comment by alemidev** [comment]
sure thing, sorry for the delay!

**Comment by alemidev** [comment]
closing, don't hesitate to reopen if i forgot anything
